name: Build

on:
  push:
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Java JDK, Node.JS and Python
    # I hope this works
    - uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - uses: actions/setup-python@v5.1.0
      with:
        python-version: 3.x
    - uses: actions/setup-java@v4.2.1
      with:
        java-version: 17.x
    - run: npm ci
    # - run: npm run test:lint
    - run: npm run prepublish
    
