name: Build

on:
  push:
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Node.JS
    # I hope this works
    # note to self, only add a - if its seperating from the other "name"
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - name: Install Python3
      uses: actions/setup-python@v5.1.0
      with:
        python-version: 3.x
    - name: Install Java JDK
      uses: actions/setup-java@v4.2.1
      with:
        java-version: 17.x
        distribution: jre
    # Finish
    - run: npm ci
    #- run: npm run test:lint
    - run: npm run prepublish
    
