name: Build

on:
  # we dont wanna build every commit as scratch-blocks is stupidly long build time
  # push:
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write

concurrency:
  group: "deploy"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Java JDK
      uses: actions/setup-java@v4.2.1
      with:
        java-version: 17.x
        distribution: adopt-openj9
        java-package: jre
    - name: Install Node.JS
    # I hope this works
    # note to self, only add a - if its seperating from the other "name"
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - name: Install Python3
      uses: actions/setup-python@v5.1.0
      with:
        python-version: 3.x
    # Build
    # CI runs prepublish automatically woops
    - run: npm ci
    #- run: npm run test:lint
    - name: Setup Git Identity 🐙
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "papersurv0+actions@gmail.com"
    - name: Push
      run: sh gh-deploy.sh
